### PR TITLE
Add entries table to readme

### PR DESCRIPTION
**Pull request by CriesofCarrots**
As of solana v1.18.0 the BigtableUploadService and `solana-ledger-tool upload` will try to populate the entries table.
Include the new table in the readme.

I didn't see any scripts that needed to be updated, since we instruct users to configure their own bigtables, but please double check I didn't miss anything.

### CODE REVIEW

**Review by joeaba — APPROVED** [review]
Awesome, thanks!

**Review by T9ipa — COMMENTED** [review]
🔥👍

**Review by T9ipa — COMMENTED** [review]
🔥👍🪃hi

**Review by T9ipa — COMMENTED** [review]
🔥👍🪃hi

**Review by T9ipa — COMMENTED** [review]
Love

**Pull request merged**
